"""Fork-child runner: one arm of a trigger-time fork (Round 3 causal design).

Spawns a child actor from a frozen fork spec (fork_collect.ForkCollector).
All children of one spec share: workspace tree at the trigger instant,
reconstructed checkpoint prompt (task + GPS + diff + bounded sources +
observations), remaining budget, and the sanitized overlay validator. Arms
differ ONLY in the intervention:

  none  — no steer; pure continuation from the reconstructed state.
  sham  — steer a decision card that is format-identical to a KAC card but
          carries no actionable content (isolates interruption/format effect).
  kac   — steer a real decision card generated by the frozen fresh-context
          probe machinery (kact.run_probe) from the snapshot state.

Steer timing is frozen: STEER_DELAY_SECONDS after child prompt start, equal
for both steered arms. Estimand note: children receive a canonical-state
reconstruction, not an exact transcript replay (pi RPC has no replay), so the
measured ATE is "card vs no card, given reconstructed state at trigger time".

Usage (key only via environment, never in a file):
  KVC_API_KEY=... python3 -m kvc.harness.run_fork_child \
      --spec <fork-spec.json> --arm kac --child 1 --run-id <id>
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import threading
import time
from pathlib import Path

from kvc.harness.fork_collect import clone_tree
from kvc.harness.gps import TriggerConfig
from kvc.harness.kact import format_card_steer, run_probe
from kvc.harness.kvc_run import KvcRunner, RunConfig
from kvc.harness.pi_bridge import load_task
from kvc.harness.providers import KEY_ENV_NAME, QWEN_FLASH_ID, dashscope_models_json

RESULTS_ROOT = Path(__file__).resolve().parents[2] / "results" / "kvc"
VALIDATE_SCRIPT = Path(__file__).resolve().parent / "validate_overlay.py"
KVC_ROOT = Path(__file__).resolve().parents[1]
PROBE_TEMPLATE = KVC_ROOT / "configs" / "prompts" / "kac_checkpoint.md"

# Frozen protocol constants (pre-registered; see DESIGN-FORK.md).
STEER_DELAY_SECONDS = 25.0
MIN_CHILD_BUDGET_SECONDS = 90.0
# Exact-replay forks resume via one user prompt, byte-identical across arms
# (arms differ ONLY in the card block steered afterwards). A resume prompt is
# unavoidable: the forked child process is idle and needs input to continue;
# the donor's own continuation has no such prompt (documented confound).
RESUME_PROMPT = (
    "Continue the task from the current state. The harness froze and resumed "
    "this session at a checkpoint; nothing was lost. Keep working."
)
MIN_SESSION_SNAPSHOT_BYTES = 512
SHAM_CARD = {
    "invariant": "Continue working toward the task goal as you understand it.",
    "edit_surface": "Not determined by this checkpoint.",
    "minimal_change": "Not determined by this checkpoint.",
    "falsifier": "Not determined by this checkpoint.",
    "next_action": "probe",
}


def objective_from_prompt(prompt: str) -> str:
    first = prompt.strip().splitlines()[0]
    return first[:120]


def build_continuation_prompt(task: dict, spec: dict, inputs: dict) -> str:
    """Reconstructed-state prompt; byte-identical across all arms of a spec."""
    parts = [
        task["prompt"],
        "",
        "[CHECKPOINT CONTINUATION]",
        "You are resuming this task from a frozen checkpoint taken "
        f"{spec['elapsed_at_trigger_seconds']:.0f}s into a previous attempt. "
        "All work done before the freeze is preserved in the workspace; "
        "do not redo it.",
        "",
        "Machine state at the freeze point (harness-maintained):",
        inputs["gps_render"],
        "",
        f"Remaining budget for this run: {spec['remaining_budget_seconds']:.0f}s. "
        "Continue the task now.",
        "",
        "Current source changes vs the base tree at the freeze point:",
        inputs["diff"],
        "",
        "Source captured at the freeze point:",
        inputs["sources"],
        "",
        inputs["observations"],
    ]
    return "\n".join(parts)


def steer_later(runner: KvcRunner, text: str, delay: float, log: dict) -> None:
    time.sleep(delay)
    log["steered_at_seconds"] = round(delay, 1)
    log["steer_accepted"] = runner.steer(text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", required=True)
    parser.add_argument("--arm", required=True, choices=("none", "sham", "kac"))
    parser.add_argument("--child", type=int, default=1)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--suite", default="v3")
    args = parser.parse_args()

    key = os.environ.get(KEY_ENV_NAME, "")
    if not key:
        print(f"FAIL: {KEY_ENV_NAME} not in environment", file=sys.stderr)
        return 2

    spec = json.loads(Path(args.spec).read_text(encoding="utf-8"))
    fork_dir = Path(args.spec).parent
    inputs = json.loads((fork_dir / "probe-input.json").read_text(encoding="utf-8"))
    task = load_task(spec["task_id"], args.suite)

    base = RESULTS_ROOT / args.run_id
    workspace = base / "workspace"
    run_dir = base / "run"
    if base.exists():
        shutil.rmtree(base)
    run_dir.mkdir(parents=True)

    fork_meta = {
        "run_id": args.run_id,
        "arm": args.arm,
        "child": args.child,
        "spec_path": args.spec,
        "donor_run_id": spec["donor_run_id"],
        "key": spec["key"],
        "trigger": spec["trigger"],
        "steer_delay_seconds": STEER_DELAY_SECONDS,
        "remaining_budget_seconds": spec["remaining_budget_seconds"],
    }

    if spec["remaining_budget_seconds"] < MIN_CHILD_BUDGET_SECONDS:
        fork_meta["skipped"] = "remaining budget below MIN_CHILD_BUDGET_SECONDS"
        run_dir.joinpath("state").mkdir(parents=True, exist_ok=True)
        (run_dir / "state" / "fork.json").write_text(
            json.dumps(fork_meta, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        print(json.dumps(fork_meta, indent=2, ensure_ascii=False))
        return 0

    # Child workspace = clone of the frozen snapshot tree.
    clone_tree(Path(spec["snapshot_path"]), workspace)

    # Mode selection: exact transcript replay (pi --fork) when the donor
    # persisted a session snapshot; canonical-state reconstruction otherwise.
    snap = spec.get("session_snapshot")
    replay = (
        bool(snap)
        and Path(snap).exists()
        and Path(snap).stat().st_size >= MIN_SESSION_SNAPSHOT_BYTES
    )
    fork_meta["fork_mode"] = "replay" if replay else "reconstruction"
    if replay:
        child_prompt = RESUME_PROMPT
    else:
        child_prompt = build_continuation_prompt(task, spec, inputs)

    # KAC arm: generate the card from the frozen snapshot state with the exact
    # probe machinery (fresh context, no tools, 120s budget) BEFORE the child
    # starts, so steer timing is comparable across steered arms.
    card = None
    if args.arm == "kac":
        probe_dir = base / "card-probe"
        probe_dir.mkdir(parents=True, exist_ok=True)
        template_text = PROBE_TEMPLATE.read_text(encoding="utf-8")
        probe_prompt = template_text.format(**inputs)
        probe_cfg = RunConfig(
            workspace=workspace,
            run_dir=run_dir,
            task_prompt=probe_prompt,
            objective_anchor=f"fork checkpoint probe {spec['key']}",
            provider="dashscope-intl",
            model=QWEN_FLASH_ID,
            thinking_level="off",
            key_env_name=KEY_ENV_NAME,
            key_value=key,
            budget_seconds=spec["remaining_budget_seconds"],
            validator_command=f"{sys.executable} {VALIDATE_SCRIPT}",
            validator_timeout_seconds=240,
            validator_task=task,
            models_json=dashscope_models_json(),
            extra_env={"PI_OFFLINE": "1"},
        )
        probe_started = time.monotonic()
        card, probe_report = run_probe(probe_cfg, spec["key"], probe_dir, probe_prompt)
        fork_meta["card_probe"] = {
            **probe_report,
            "duration_seconds": round(time.monotonic() - probe_started, 1),
        }
        fork_meta["card"] = card

    config = RunConfig(
        workspace=workspace,
        run_dir=run_dir,
        task_prompt=child_prompt,
        objective_anchor=objective_from_prompt(task["prompt"]),
        provider="dashscope-intl",
        model=QWEN_FLASH_ID,
        thinking_level="off",
        key_env_name=KEY_ENV_NAME,
        key_value=key,
        budget_seconds=spec["remaining_budget_seconds"],
        validator_command=f"{sys.executable} {VALIDATE_SCRIPT}",
        validator_timeout_seconds=240,
        validator_task=task,
        models_json=dashscope_models_json(),
        extra_env={"PI_OFFLINE": "1"},
        # Children never fire triggers: the intervention is fixed per arm.
        trigger_config=TriggerConfig(
            no_mutation_budget_ratio=float("inf"), post_pass_tool_calls=10**9
        ),
        fork_session_path=Path(snap) if replay else None,
    )
    runner = KvcRunner(config)
    # Runner prep creates run_dir/state; keep child metadata inside run_dir.

    steer_log: dict = {}
    steer_thread = None
    runner.start()
    try:
        if args.arm == "sham":
            steer_text = format_card_steer(spec["key"], SHAM_CARD, spec["trigger"])
            steer_thread = threading.Thread(
                target=steer_later, args=(runner, steer_text, STEER_DELAY_SECONDS, steer_log),
                daemon=True,
            )
            steer_thread.start()
        elif args.arm == "kac" and card is not None:
            steer_text = format_card_steer(spec["key"], card, spec["trigger"])
            steer_thread = threading.Thread(
                target=steer_later, args=(runner, steer_text, STEER_DELAY_SECONDS, steer_log),
                daemon=True,
            )
            steer_thread.start()
        elif args.arm == "kac":
            fork_meta["card_note"] = "probe produced no parseable card; child runs unsteered"
        outcome = runner.run_prompt(child_prompt)
    finally:
        if runner._proc and runner._proc.poll() is None:
            runner.finish()

    # Primary outcome: any passing frozen-verifier validation during the child.
    final_pass = False
    first_pass_epoch = None
    events_path = run_dir / "events" / "events.jsonl"
    if events_path.exists():
        for line in events_path.read_text(encoding="utf-8").splitlines():
            try:
                frame = json.loads(line)
            except json.JSONDecodeError:
                continue
            if frame.get("type") == "kvc_validation" and frame.get("result") == "pass":
                final_pass = True
                if first_pass_epoch is None:
                    first_pass_epoch = frame.get("epoch")

    fork_meta.update(steer_log)
    (run_dir / "state" / "fork.json").write_text(
        json.dumps(fork_meta, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (run_dir / "state" / "child-prompt.txt").write_text(child_prompt, encoding="utf-8")
    report = {
        "run_id": args.run_id,
        "task": spec["task_id"],
        "arm": args.arm,
        "fork_key": spec["key"],
        "donor_run_id": spec["donor_run_id"],
        "reason": outcome.reason,
        "final_pass": final_pass,
        "first_pass_epoch": first_pass_epoch,
        "duration_seconds": outcome.duration_seconds,
        "mutation_epochs": outcome.epochs,
        "validation_calls": outcome.validations,
        "peak_rss_mb": outcome.peak_rss_mb,
        "run_dir": str(run_dir),
    }
    (base / "report.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(json.dumps(report, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
